"""Tallas y colores con stock independiente por talla; vendedor y nombre de cliente en ventas

Revision ID: 8652afa81dae
Revises: 5030ba90076f
Create Date: 2026-07-31 23:23:08.131914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8652afa81dae'
down_revision = '5030ba90076f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_productstock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'talla', 'color', name='uq_product_talla_color')
    )

    # Migra los datos existentes de "stock por color" (inventory_productcolorstock)
    # hacia el nuevo esquema "stock por talla + color", usando la talla que ya
    # tenía cada producto (o 'Única' si no tenía ninguna) como talla inicial.
    # Así ningún producto/color ya cargado pierde su stock en la migración.
    op.execute(sa.text("""
        INSERT INTO inventory_productstock (product_id, talla, color, stock)
        SELECT pcs.product_id,
               CASE WHEN p.talla IS NULL OR p.talla = '' THEN 'Única' ELSE p.talla END,
               pcs.color,
               pcs.stock
        FROM inventory_productcolorstock pcs
        JOIN inventory_product p ON p.id = pcs.product_id
    """))

    # Productos que nunca tuvieron desglose por color (solo el total
    # "Existencias" del formulario anterior): se crea una sola fila con
    # su talla y el total que ya tenían, para no dejarlos sin inventario.
    op.execute(sa.text("""
        INSERT INTO inventory_productstock (product_id, talla, color, stock)
        SELECT p.id,
               CASE WHEN p.talla IS NULL OR p.talla = '' THEN 'Única' ELSE p.talla END,
               '',
               p.stock_quantity
        FROM inventory_product p
        WHERE p.id NOT IN (SELECT DISTINCT product_id FROM inventory_productcolorstock)
          AND p.stock_quantity > 0
    """))

    op.drop_table('inventory_productcolorstock')
    with op.batch_alter_table('sales_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('vendedor', sa.String(length=150), nullable=True))

    with op.batch_alter_table('sales_saleitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talla_vendida', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_saleitem', schema=None) as batch_op:
        batch_op.drop_column('talla_vendida')

    with op.batch_alter_table('sales_sale', schema=None) as batch_op:
        batch_op.drop_column('vendedor')
        batch_op.drop_column('client_name')

    op.create_table('inventory_productcolorstock',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=100), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'color', name='uq_product_color')
    )
    op.drop_table('inventory_productstock')
    # ### end Alembic commands ###
